### ISSUE TITLE
Redesign issues checklist

### ISSUE THREAD

**Issue by vala** [para-cms/para#59]
This a checklist to store redesign issues or todos :

- [ ] Color picker input doesn't display well when empty (Simple Form Extension `:color` input)
- [ ] Nested many `:inset` display is ugly for now
- [ ] Custom [Stall](https://github.com/rails-stall/stall) inputs are not designed for now
